# Site settings
title: On the Road to Sebbe's Blog
description: "This is mockup-2 of Sebbe's blog."
baseurl: "/sebbe02" 
url: "http://virsto.github.io/sebbe02" 
tagline: A basic guide to Jekyll

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
# The following is required for jekyll vers. 3+
gems: [jekyll-paginate]	
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
